### ISSUE TITLE
Class 'app\assets\AppAsset' not found

### ISSUE THREAD

**Issue by hikmat30ce** [sadiyafarheen/projectfollowups#1]
I have deployed it on http://projectfollowups.hikmatu.com/user/login and below error is shown

Error: Class 'app\assets\AppAsset' not found in /app/views/layouts/main.php:16
Stack trace:
#0 /app/vendor/yiisoft/yii2/base/View.php(336): require()
#1 /app/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile('/app/views/layo...', Array)
#2 /app/vendor/yiisoft/yii2/base/Controller.php(399): yii\base\View->renderFile('/app/views/layo...', Array, Object(dektrium\user\controllers\SecurityController))
#3 /app/vendor/yiisoft/yii2/base/Controller.php(385): yii\base\Controller->renderContent('\n\n    <div clas...')
#4 /app/vendor/dektrium/yii2-user/controllers/SecurityController.php(166): yii\base\Controller->render('login', Array)
#5 [internal function]: dektrium\user\controllers\SecurityController->actionLogin()
#6 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#8 /app/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('login', Array)
#9 /app/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/security/l...', Array)
#10 /app/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#11 /app/index.php(12): yii\base\Application->run()
#12 {main}
Copy Stacktrace Search Stackoverflow Search Google Exception
Error
Class 'app\assets\AppAsset' not found

It seems the configurations are different from the running project or some files are not uploaded into github

**Comment by sadiyafarheen** [comment]
fixed, please check
